updated all readme files
Spikes-2212-Programming-Guild/SpikesLib2-Examples pull request #12
Opened 2022-03-13 18:58 UTC by OfriRosenbaum

2022-03-14 15:56 UTC, Yoel-Perman-Brilliant requested changes

2022-03-14 15:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/drivetrains/advancedtankdrivetrain/README.md
>  ![drivetrain](https://imgur.com/dfjdcg6.png)
put the picture first

2022-03-14 15:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/drivetrains/simpletankdrivetrain/README.md
>  ![drivetrain](https://imgur.com/dfjdcg6.png)
put the picture first

2022-03-14 15:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/climber/README.md
> +![climber arm](https://imgur.com/J6VwdEP.png)
put the picture first

2022-03-14 15:56 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/gripper/README.md
>  ![empty gripper](https://imgur.com/vyKXnYx.png)
I think you get the point

2022-03-14 18:20 UTC, Yoel-Perman-Brilliant requested changes

2022-03-14 18:20 UTC, Yoel-Perman-Brilliant commented on README.md
> +    - Each interface in RobotMap represents a different type port.
type of port

2022-03-14 18:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/drivetrains/advancedtankdrivetrain/README.md
> +- Change the PID, FeedForward and distance per pulse in [Drivetrain](Drivetrain.java)
PID constants, Feed Forward gains

2022-03-14 18:20 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/shooter/README.md
> +- Change the type of MotorController in [Shooter](Shooter.java) (if you change this, you __must__ also change the
Not necessarily must, They might be using a falcon which also has a talon encoder

2022-03-15 07:59 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/advancedtankdrivetrain/README.md
>  ![drivetrain](https://imgur.com/dfjdcg6.png)
no

2022-03-15 13:43 UTC, Yoel-Perman-Brilliant requested changes

2022-03-15 13:43 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/shooter/README.md
> +- Change the type of MotorController in [Shooter](Shooter.java) (if you change this, you may also need change the
need to change

2022-03-24 18:22 UTC, Spikes-2212 requested changes
change `may` to `might` everywhere

2022-03-24 18:22 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/shooter/README.md
> +- Change the type of MotorController in [Shooter](Shooter.java) (if you change this, you might also need change the
you might also need **to** change...

2022-12-29 18:36 UTC, TurtleMinecraft approved these changes

2022-12-29 18:41 UTC, merged