Drivetrain
Spikes-2212-Programming-Guild/SpikesLib2-Examples pull request #3
Opened 2022-02-20 18:42 UTC by Yoel-Perman-Brilliant

2022-02-20 18:51 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Robot.java
> +     * A namespace is an object which holds value on a {@link NetworkTable}.
you dont have to explain it **EVERY TIME**

2022-02-20 18:53 UTC, tal-sitton requested changes
In general, plz remove all the pre-written docs in Robot.java

2022-02-20 18:53 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Robot.java
> +     * A namespace is an object which holds value on a {@link NetworkTable}.
you dont have to explain it **EVERY TIME**

2022-02-20 18:53 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Robot.java
> +     * constructs an instance of OI - a class for interfacing with the robot.
this is not the right description

2022-02-21 12:34 UTC, tal-sitton requested changes

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * <p>
you opened a paragraph, but.... have you closed it?

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * Since they were made using {@code addConstantDouble}, they are constants relative to the code itself, but are
repetitive

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * Since they were made using {@code addConstantDouble}, they are constants relative to the code itself, but are
repetitive

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    public double getLeftDistance() {
have you configured distance per pulse?
this will return the pulse, because no distancePerPulse was given

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    public double getRightDistance() {
ditto

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +        rootNamespace.putData("reset gyro", new InstantCommand(this::resetGyro));
add `drive forward` and `drive backward` to the shuffleboard.

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Main.java
no need to touch this class

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/OI.java
> + * An object which represents an OI, which handles the active control over the robot from the user's side.
`An object which represents an OI` - no kidding.
remove

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/OI.java
> +public class OI /*GEVALD*/{
add space after the `/`

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/OI.java
> +    private final Joystick leftJoystick;
initialize the joystick here

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/OI.java
> +    private final Joystick rightJoystick;
initialize the joystick here

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/OI.java
> +        leftJoystick = new Joystick(0);
remove

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/OI.java
> +        rightJoystick = new Joystick(1);
remove

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Robot.java
> +     * <p>
you opened a paragraph, but.... have you closed it?

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Robot.java
> +    private final OI oi = new OI();
oi should be initialized in `robotInit()`

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/OI.java
> +    public double getLeftY() {
why is this here?

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/OI.java
> +    public double getRightX() {
ditto

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/RobotMap.java
> + * A class which holds the ports of the devices which are connected to the robot.
why is this a paragraph?

2022-02-21 12:34 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/RobotMap.java
> + * TODO: remove documentation once there is a readme
no, do it now!

2022-02-21 16:36 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/RobotMap.java
> + * TODO: remove documentation once there is a readme
it's in update_readme, you just gotta approve it

2022-02-21 17:38 UTC, tal-sitton requested changes

2022-02-21 17:38 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * Constants which are used for fixing the drivetrain's deviation. More info in {@link BustedMotorControllerGroup}.
change `which` to `that`

2022-02-21 17:38 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    private final Supplier<Double> kG = rootNamespace.addConstantDouble("kG", 0);
why is `kG` here? its a drivetrain

2022-02-21 17:38 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    private final Supplier<Double> TOLERANCE = rootNamespace.addConstantDouble("TOLERANCE", 0);
why is my shuffleboard yelling?
(why all caps in shuffleboard)

2022-02-21 17:38 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    private final Supplier<Double> WAIT_TIME = rootNamespace.addConstantDouble("WAIT_TIME", 1);
why is my shuffleboard yelling?
(why all caps in shuffleboard)

2022-02-21 18:18 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    private final Supplier<Double> TOLERANCE = rootNamespace.addConstantDouble("TOLERANCE", 0);
it's a constant

2022-02-21 18:18 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    private final Supplier<Double> WAIT_TIME = rootNamespace.addConstantDouble("WAIT_TIME", 1);
it's a constant

2022-02-21 19:06 UTC, OfriRosenbaum requested changes

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * <p>
convention B-I\b9 - Use both opening and closing tags for paragraph separation, **both inlined**

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * </p>
convention B-I\b9 - Use both opening and closing tags for paragraph separation, **both inlined**

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * A namespace is an object which holds value on a {@link NetworkTable}.
does it hold only one value?

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/RobotMap.java
> +        int LEFT_ENCODER_A = 0;
Convention A-II/b2, the first line in a class is blank

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/feeder/RobotMap.java
> +        int FEEDER_VICTOR = 0;
![image](https://user-images.githubusercontent.com/71877371/155012422-43b67bca-c3d6-4f8b-b87b-c2506cfc4d95.png)

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Robot.java
> +    private final Drivetrain drivetrain = Drivetrain.getInstance();
use the `configureDashboard()` in `robotInit()`

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Robot.java
> +     * A namespace is an object which holds value on a {@link NetworkTable}.
does it hold only value?

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Robot.java
> +     * <p>
convention B-I\b9 - Use both opening and closing tags for paragraph separation, **both inlined**

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Robot.java
> +     * </p>
convention B-I\b9 - Use both opening and closing tags for paragraph separation, **both inlined**

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Robot.java
> +        /*
add a blank line before the javadoc

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/OI.java
> +    private final Joystick leftJoystick = new Joystick(0);
Convention A-II/b2, the first line in a class is blank

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Main.java
> +import frc.robot.subsystems.climber.Robot;
![image](https://user-images.githubusercontent.com/71877371/155013236-7f324dd1-bf91-4945-a238-826d9790781b.png)

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    public double getAngle() {
this method is simply incorrect

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +
remove blank line

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * sets the values which appear on the shuffleboard using a {@link Namespace}.
Capital letter at the start of a sentence

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * Constants for a feed forward controller. More info in {@link FeedForwardController}.
make it a `@link`, and remove the "More info in..." part

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * The wheel moves 15.24 * PI (its perimeter) each 360 ticks (in meters).
What is distance per pulse?

2022-02-21 19:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +            instance.configureDashboard();
use `configureDashboard()` in `robotInit()`, not here

2022-02-21 19:18 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    public double getAngle() {
u no

2022-02-27 16:18 UTC, tal-sitton requested changes

2022-02-27 16:18 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> + * In addition, this drivetrain includes encoders, settings for PID and FeedForward controllers, and communication with
and GYRO

2022-02-27 16:18 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * <p> A namespace is an object which holds values on a {@link NetworkTable}. </p>
object `that` holds

2022-02-27 16:18 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    private static Drivetrain instance;
explain that this is singleton

2022-02-27 16:18 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/OI.java
> + * Handles the active control over the robot from the user's side.
change

2022-02-27 16:18 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Robot.java
> +     * <p> A namespace is an object which holds value on a {@link NetworkTable}.</p>
ditto

2022-02-27 16:18 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/feeder/RobotMap.java
> +        int FEEDER_VICTOR = 0;
![image](https://user-images.githubusercontent.com/53299816/155890362-6aa0dbd0-a202-4186-b343-a3d24acdf33d.png)

2022-03-03 19:29 UTC, tal-sitton requested changes

2022-03-03 19:29 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * <p> A namespace is an object that holds values on a {@link NetworkTable}. </p>
`in a...`

2022-03-03 19:29 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +     * The wheel moves 15.24 * PI (its perimeter) each 360 ticks (in meters).
change `The` to `This` or `Our`

2022-03-03 19:29 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    public void configureDashboard() {
add the option to drive for 2 meters using PID

2022-03-05 11:30 UTC, tal-sitton approved these changes

2022-03-05 11:30 UTC, tal-sitton commented on src/main/java/frc/robot/drivetrains/tankdrivetrain/Drivetrain.java
> +    private final Supplier<Double> kP = rootNamespace.addConstantDouble("kP", 0);
change to 1

2022-03-05 16:45 UTC, merged