Ofri climber example
Spikes-2212-Programming-Guild/SpikesLib2-Examples pull request #5
Opened 2022-02-20 19:34 UTC by OfriRosenbaum

2022-02-21 12:23 UTC, tal-sitton requested changes

2022-02-21 12:23 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    public final Supplier<Double> DOWN_SPEED = rootNamespace.addConstantDouble("down speed", -0.4);
you don't need `MAX_SPEED` and `MIN_SPEED` if you have `UP_SPEED` and `DOWN_SPEED`

2022-02-24 06:15 UTC, tal-sitton requested changes

2022-02-24 06:15 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +     * <p>A game that this example subsystem can be used in is 2020 FRC INFINITE RECHARGE</p>
you know that this year (2022) we also have to climb... right?

2022-02-24 06:15 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    /**
Javadoc of a class should be before `public class....`

2022-02-24 06:15 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    public Climber(WPI_VictorSPX motor) {
why public?

2022-03-03 19:22 UTC, tal-sitton requested changes

2022-03-03 19:22 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> + * A game that this example subsystem can be used in is FRC Rapid React 2022.
explain what is this subsystem

2022-03-05 12:52 UTC, Yoel-Perman-Brilliant requested changes, later dismissed

2022-03-05 12:52 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +    private static Climber instance;
explain

2022-03-05 16:56 UTC, tal-sitton requested changes

2022-03-05 16:56 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> + * A game that this example subsystem can be used in is FRC Rapid React 2022.
why did you write `FRC`? isn't it obvious?

2022-03-05 16:56 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +     * With only a private constructor and a single private instance with a public getter, the singleton design pattern
sounds like a copy-paste from some Shakespeare book. CHANGE

2022-03-05 18:18 UTC, tal-sitton requested changes

2022-03-05 18:18 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> + * A subsystem which represents a climber. The climber consists of an arm that is controlled by a VictorSPX. The arm
we know this class represents a climber, its in the name

2022-03-05 18:18 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/climber/Climber.java
> +     * The Climber class is a singleton, which means it has only one instance. Since the constructor is private, a new
"But why would you want it to be singleton?" ~ a random programmer

2022-03-06 09:48 UTC, tal-sitton approved these changes

2022-03-06 10:07 UTC, merged