Transfer
Spikes-2212-Programming-Guild/SpikesLib2-Examples pull request #8
Opened 2022-03-06 18:44 UTC by Yoel-Perman-Brilliant

2022-03-06 19:26 UTC, OfriRosenbaum requested changes

2022-03-06 19:26 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/transfer/Robot.java
> +    /*
you don't do javadoc inside a method.

2022-03-06 19:26 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/transfer/Robot.java
> +  public void robotPeriodic() {
add the periodic of the `robotNamespace`

2022-03-06 19:26 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/transfer/Robot.java
> +  MotoredGenericSubsystem transfer;
default visibility modifier?

2022-03-06 19:28 UTC, OfriRosenbaum requested changes

2022-03-06 19:28 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/transfer/Robot.java
> +  public void robotPeriodic() {
also add the periodic of `transfer`

2022-03-06 19:30 UTC, OfriRosenbaum requested changes

2022-03-06 19:30 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/transfer/Robot.java
> +     * Places a command which moves the transfer subsystem on the SmartDashboard.
change SmartDashboard to `{@link Shuffleboard}`

2022-03-07 06:51 UTC, tal-sitton requested changes

2022-03-07 06:51 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/transfer/Robot.java
> +    private RootNamespace robotNamespace;
initialize the namespace here

2022-03-07 06:51 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/transfer/Robot.java
> +     * puts pressure on a cargo, and thus the cargo moves along with the strap.
puts pressure on a `ball`, 
`cargo` is too specific

2022-03-07 08:25 UTC, tal-sitton requested changes

2022-03-07 08:25 UTC, tal-sitton commented on src/main/java/frc/robot/subsystems/transfer/Robot.java
> +     * puts pressure on a ball, and thus the cargo moves along with the strap.
again, `cargo`?

2022-03-08 08:36 UTC, merged